# Generated by Django 5.0.1 on 2024-01-17 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('AnaDepo', 'Ana Depo'), ('AraDepo', 'Ara Depo'), ('MağazaDepo', 'Mağaza Depo')], max_length=30)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desi', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='uygulama_adi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('SevkEdildi', 'Sevk Edildi'), ('TeslimEdildi', 'Teslim Edildi')], max_length=30)),
                ('destination_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_destination', to='uygulama_adi.depot')),
                ('source_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='uygulama_adi.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.product')),
                ('store', models.ForeignKey(limit_choices_to={'type': 'MağazaDepo'}, on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.depot')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('min_required', models.PositiveIntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('destination_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='uygulama_adi.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama_adi.product')),
                ('source_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='uygulama_adi.depot')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='staff_manager', max_length=50)),
                ('depotname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uygulama_adi.depot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
