# Generated by Django 5.0.1 on 2024-01-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama_adi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierOrder',
        ),
    ]
